export default [
  {
    type: "Greetings",
    list: [
      "hello",
      "hi",
      "hey there",
      "good to see you",
      "good afternoon ",
      "good morning",
      "good evening",
      "Long time no see",
      "How are you?",
      "I'm fine",
      "I'm good",
      "I'm okay",
      "I'm tired",
      "I'm",
      "What's up?",
      "not much",
      "same as usual",
      "pretty good",
      "How's it going?",
      "everything is good",
      "not good",
      "busy",
      "I don't know",
      "maybe",
      "yes",
      "no",
    ],
  },
  {
    type: "Closures",
    list: [
      "goodbye",
      "see you later",
      "bye",
      "time to go",
      "see you tomorrow",
      "later",
      "have a nice weekend",
      "take care",
      "see you",
      "good night",
      "see you soon",
      "see you around",
      "later gator",
      "nice to meet you",
      "talk to you later",
    ],
  },
  {
    type: "Maintainers",
    list: [
      "That's cool",
      "wow",
      "I don't want to",
      "I don't like",
      "that's funny",
      "oh my",
      "that's awesome",
      "I love it",
      "no way",
      "not fair",
      "ha ha ha",
      "come on",
      "I like that",
      "I agree",
      "nope",
      "too bad",
      "whatever",
      "then what happened?",
      "you're right",
      "that's good",
      "I'm sorry",
      "I don't think so",
      "really",
      "uh oh",
      "I don't know",
      "probably",
      "I know",
      "nice",
      "you're wrong",
      "not good",
      "can't believe that",
      "maybe",
      "ok",
      "oh",
    ],
  },
  {
    type: "Regulators",
    list: [
      "I need a break",
      "leave me alone",
      "go away",
      "I want to go on the swing",
      "I'm thirsty",
      "I'm hungry",
    ],
  },

  {
    type: "Questions",
    list: [
      "How was your weekend?",
      "Where did you go?",
      "How's your day?",
      "How is your family?",
      "What plans do you have for today?",
      "What are you doing after school?",
      "How was your day?",
      "What did you do?",
      "Where are you going?",
      "What are you doing later?",
      "What about you?",
      "What's new?",
      "What happened next?",
      "Do you want to play?",
      "hang out?",
      "What's next?",
    ],
  },

  {
    type: "Repairs",
    list: [
      "you're way off",
      "It starts with",
      "Let me try to spell it.",
      "it sounds like ",
      "it's like this but different",
      "you're getting closer",
      "that's not what I said",
      "Please add a word to my device.",
      "let me show you",
      "Let me show you a picture.",
      "I can't show you, it's not here.",
      "It's not on my device",
      "I don't know where to find it",
      "I'm using this app to help me speak",
      "give me a minute to finish my message.",
      "don't guess what I am trying to say",
      "I made a mistake",
      "I don't understand",
      "say that again",
      "ask me a yes/no question",
      "please guess what I am saying",
      "yes",
      "no",
    ],
  },

  {
    type: "Places",
    list: [
      "go",
      "chair",
      "desk",
      "address",
      "stove",
      "fridge",
      "church",
      "hospital",
      "restaurant",
      "school",
      "post office",
      "building",
      "bathroom",
      "bath",
      "sink",
      "hotel",
      "theater",
      "library",
      "bank",
      "subway",
      "farm",
      "bed",
      "closet",
      "drawer",
      "sidewalk",
      "street",
      "college",
      "shop",
      "store",
      "house",
      "hall",
      "room",
      "floor",
      "ceiling",
    ],
  },

  {
    type: "Manners",
    list: [
      "please",
      "thank you",
      "you're welcome",
      "excuse me",
      "I'm sorry",
      "I promise",
      "I didn't mean it",
      "it was an accident",
      "I forgot",
      "say you're sorry",
      "bless you",
      "no problem",
      "that's okay",
    ],
  },
  {
    type: "Personal",
    list: [
      "this is my ",
      "My name is ",
      "What's your name?",
      "I live at ",
      "Where do you live?",
      "My birthday is",
      "When is your birthday?",
      "I am   years old.",
      "How old are you?",
      "I go to school at ",
      "Where do you go to school?",
      "My phone number is ",
      "What's your phone number?",
      "My cell phone number is",
      "What's your cell phone number?",
      "My email address is",
      "What's your email address?",
      "How about you?",
      "I work at ",
      "What kind of work do you do?",
      "I like to ",
      "What do you like to do?",
      "I have a ",
      "Do you have any pets?",
      "My favorite TV show is",
      "What's your favorite TV show?",
      "Where are you from?",
      "nice to meet you",
      "I don't think we met.",
    ],
  },
  {
    type: "Calls",
    list: [
      "May I talk to ",
      "This is Hannah, please call me back",
      "I use a speech-generating device to talk, please don't hangup while I make my message.",
      "call me back at ",
      "Message 1",
      "Message 2",
      "Message 3",
    ],
  },
  {
    type: "News",
    list: ["You know what I did?", "Want to hear what I did?", "Guess what?"],
  },
  {
    type: "People",
    list: [
      "mom",
      "dad",
      "grandma",
      "grandpa",
      "they",
      "he",
      "him",
      "her",
      "she",
      "sister",
      "brother",
    ],
  },
];
